Add clang-format check to CI

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -6,6 +6,7 @@ variables:
 stages:
     - build
     - test
+    - lint
 
 before_script:
     # Configure gitlab runner credentials.
@@ -18,7 +19,7 @@ before_script:
     # Install required packages.
     - apt-get update
     - apt-get -y install
-        cmake ninja-build build-essential git mingw-w64 binutils-mingw-w64 gcc-8 g++-8
+        cmake ninja-build build-essential git mingw-w64 binutils-mingw-w64 gcc-8 g++-8 clang-format
     - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 700 --slave /usr/bin/g++ g++ /usr/bin/g++-7
     - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8
     # Initialize submodules.
@@ -67,3 +68,11 @@ test:linux:
         key: "$CI_PROJECT_PATH_SLUG $CI_COMMIT_SHA linux"
         paths:
             - build/
+
+lint:linux:
+    stage: lint
+    script:
+        - if (clang-format $(find src tests -name "*.[ch]pp") -output-replacements-xml | grep -c "<replacement " >/dev/null); then
+            echo "Linter errors found, please run clang-format and try again";
+            exit 1;
+          fi
